trigger:
  branches:
    include:
      - main

pool: LocalPool1

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'pradeesh2610/newsample1'  # Name of the artifact published in the previous job
    path: 'C:/Softwares'  # Path to download the files to