trigger:
  branches:
    include:
      - main

pool: LocalPool1

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'github-repo-artifact'  # Name of the artifact published in the previous job
    path: '$(Pipeline.Workspace)/downloaded-files'  # Path to download the files to